//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CSLSite.SI_Customer_Statement_NAVIS_CGSA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Ws_Sap_EstadoDeCuentaSoap", Namespace="http://localhost/Ws_Sap_EstadoDeCuenta")]
    public partial class Ws_Sap_EstadoDeCuenta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_Customer_Statement_NAVIS_CGSAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Ws_Sap_EstadoDeCuenta() {
            this.Url = global::CSLSite.Properties.Settings.Default.CSLSite_SI_Customer_Statement_NAVIS_CGSA_Ws_Sap_EstadoDeCuenta;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_Customer_Statement_NAVIS_CGSACompletedEventHandler SI_Customer_Statement_NAVIS_CGSACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/Ws_Sap_EstadoDeCuenta/SI_Customer_Statement_NAVIS_CGSA", RequestNamespace="http://localhost/Ws_Sap_EstadoDeCuenta", ResponseNamespace="http://localhost/Ws_Sap_EstadoDeCuenta", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode SI_Customer_Statement_NAVIS_CGSA(string EMPE_RUC, string USER_NAME, string PASSWORD) {
            object[] results = this.Invoke("SI_Customer_Statement_NAVIS_CGSA", new object[] {
                        EMPE_RUC,
                        USER_NAME,
                        PASSWORD});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void SI_Customer_Statement_NAVIS_CGSAAsync(string EMPE_RUC, string USER_NAME, string PASSWORD) {
            this.SI_Customer_Statement_NAVIS_CGSAAsync(EMPE_RUC, USER_NAME, PASSWORD, null);
        }
        
        /// <remarks/>
        public void SI_Customer_Statement_NAVIS_CGSAAsync(string EMPE_RUC, string USER_NAME, string PASSWORD, object userState) {
            if ((this.SI_Customer_Statement_NAVIS_CGSAOperationCompleted == null)) {
                this.SI_Customer_Statement_NAVIS_CGSAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_Customer_Statement_NAVIS_CGSAOperationCompleted);
            }
            this.InvokeAsync("SI_Customer_Statement_NAVIS_CGSA", new object[] {
                        EMPE_RUC,
                        USER_NAME,
                        PASSWORD}, this.SI_Customer_Statement_NAVIS_CGSAOperationCompleted, userState);
        }
        
        private void OnSI_Customer_Statement_NAVIS_CGSAOperationCompleted(object arg) {
            if ((this.SI_Customer_Statement_NAVIS_CGSACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_Customer_Statement_NAVIS_CGSACompleted(this, new SI_Customer_Statement_NAVIS_CGSACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void SI_Customer_Statement_NAVIS_CGSACompletedEventHandler(object sender, SI_Customer_Statement_NAVIS_CGSACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_Customer_Statement_NAVIS_CGSACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_Customer_Statement_NAVIS_CGSACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591