//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSLSite {


    public partial class DespachoVehiculos {

        /// <summary>
        /// tkscata control.
        /// </summary>
        protected global::AjaxControlToolkit.ToolkitScriptManager tkscata;

        /// <summary>
        /// UPBUSCAR control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel UPBUSCAR;

        /// <summary>
        /// TXTMRN control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TXTMRN;

        /// <summary>
        /// TXTMSN control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TXTMSN;

        /// <summary>
        /// TXTHSN control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TXTHSN;

        /// <summary>
        /// BtnBuscar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnBuscar;

        /// <summary>
        /// banmsg control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl banmsg;

        /// <summary>
        /// UPDETALLE control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel UPDETALLE;

        /// <summary>
        /// gvContenedores control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvContenedores;
    }
}
