//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSLSite.swNeuroOC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="swNeuroOC.wsNeuroSoap")]
    public interface wsNeuroSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento base64Input del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/imageToIcao", ReplyAction="*")]
        CSLSite.swNeuroOC.imageToIcaoResponse imageToIcao(CSLSite.swNeuroOC.imageToIcaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/imageToIcao", ReplyAction="*")]
        System.Threading.Tasks.Task<CSLSite.swNeuroOC.imageToIcaoResponse> imageToIcaoAsync(CSLSite.swNeuroOC.imageToIcaoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento base64Input del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/imageToTemplate", ReplyAction="*")]
        CSLSite.swNeuroOC.imageToTemplateResponse imageToTemplate(CSLSite.swNeuroOC.imageToTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/imageToTemplate", ReplyAction="*")]
        System.Threading.Tasks.Task<CSLSite.swNeuroOC.imageToTemplateResponse> imageToTemplateAsync(CSLSite.swNeuroOC.imageToTemplateRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento base64Input1 del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyImage", ReplyAction="*")]
        CSLSite.swNeuroOC.VerifyImageResponse VerifyImage(CSLSite.swNeuroOC.VerifyImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyImage", ReplyAction="*")]
        System.Threading.Tasks.Task<CSLSite.swNeuroOC.VerifyImageResponse> VerifyImageAsync(CSLSite.swNeuroOC.VerifyImageRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento base64Input1 del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyTemplate", ReplyAction="*")]
        CSLSite.swNeuroOC.VerifyTemplateResponse VerifyTemplate(CSLSite.swNeuroOC.VerifyTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyTemplate", ReplyAction="*")]
        System.Threading.Tasks.Task<CSLSite.swNeuroOC.VerifyTemplateResponse> VerifyTemplateAsync(CSLSite.swNeuroOC.VerifyTemplateRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento licenseStatusResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/licenseStatus", ReplyAction="*")]
        CSLSite.swNeuroOC.licenseStatusResponse licenseStatus(CSLSite.swNeuroOC.licenseStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/licenseStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<CSLSite.swNeuroOC.licenseStatusResponse> licenseStatusAsync(CSLSite.swNeuroOC.licenseStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class imageToIcaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="imageToIcao", Namespace="http://tempuri.org/", Order=0)]
        public CSLSite.swNeuroOC.imageToIcaoRequestBody Body;
        
        public imageToIcaoRequest() {
        }
        
        public imageToIcaoRequest(CSLSite.swNeuroOC.imageToIcaoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class imageToIcaoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Input;
        
        public imageToIcaoRequestBody() {
        }
        
        public imageToIcaoRequestBody(string base64Input) {
            this.base64Input = base64Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class imageToIcaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="imageToIcaoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSLSite.swNeuroOC.imageToIcaoResponseBody Body;
        
        public imageToIcaoResponse() {
        }
        
        public imageToIcaoResponse(CSLSite.swNeuroOC.imageToIcaoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class imageToIcaoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string imageToIcaoResult;
        
        public imageToIcaoResponseBody() {
        }
        
        public imageToIcaoResponseBody(string imageToIcaoResult) {
            this.imageToIcaoResult = imageToIcaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class imageToTemplateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="imageToTemplate", Namespace="http://tempuri.org/", Order=0)]
        public CSLSite.swNeuroOC.imageToTemplateRequestBody Body;
        
        public imageToTemplateRequest() {
        }
        
        public imageToTemplateRequest(CSLSite.swNeuroOC.imageToTemplateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class imageToTemplateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Input;
        
        public imageToTemplateRequestBody() {
        }
        
        public imageToTemplateRequestBody(string base64Input) {
            this.base64Input = base64Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class imageToTemplateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="imageToTemplateResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSLSite.swNeuroOC.imageToTemplateResponseBody Body;
        
        public imageToTemplateResponse() {
        }
        
        public imageToTemplateResponse(CSLSite.swNeuroOC.imageToTemplateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class imageToTemplateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string imageToTemplateResult;
        
        public imageToTemplateResponseBody() {
        }
        
        public imageToTemplateResponseBody(string imageToTemplateResult) {
            this.imageToTemplateResult = imageToTemplateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyImage", Namespace="http://tempuri.org/", Order=0)]
        public CSLSite.swNeuroOC.VerifyImageRequestBody Body;
        
        public VerifyImageRequest() {
        }
        
        public VerifyImageRequest(CSLSite.swNeuroOC.VerifyImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Input1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string base64Input2;
        
        public VerifyImageRequestBody() {
        }
        
        public VerifyImageRequestBody(string base64Input1, string base64Input2) {
            this.base64Input1 = base64Input1;
            this.base64Input2 = base64Input2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSLSite.swNeuroOC.VerifyImageResponseBody Body;
        
        public VerifyImageResponse() {
        }
        
        public VerifyImageResponse(CSLSite.swNeuroOC.VerifyImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerifyImageResult;
        
        public VerifyImageResponseBody() {
        }
        
        public VerifyImageResponseBody(string VerifyImageResult) {
            this.VerifyImageResult = VerifyImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyTemplateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyTemplate", Namespace="http://tempuri.org/", Order=0)]
        public CSLSite.swNeuroOC.VerifyTemplateRequestBody Body;
        
        public VerifyTemplateRequest() {
        }
        
        public VerifyTemplateRequest(CSLSite.swNeuroOC.VerifyTemplateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyTemplateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Input1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string base64Input2;
        
        public VerifyTemplateRequestBody() {
        }
        
        public VerifyTemplateRequestBody(string base64Input1, string base64Input2) {
            this.base64Input1 = base64Input1;
            this.base64Input2 = base64Input2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyTemplateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyTemplateResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSLSite.swNeuroOC.VerifyTemplateResponseBody Body;
        
        public VerifyTemplateResponse() {
        }
        
        public VerifyTemplateResponse(CSLSite.swNeuroOC.VerifyTemplateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyTemplateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerifyTemplateResult;
        
        public VerifyTemplateResponseBody() {
        }
        
        public VerifyTemplateResponseBody(string VerifyTemplateResult) {
            this.VerifyTemplateResult = VerifyTemplateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class licenseStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="licenseStatus", Namespace="http://tempuri.org/", Order=0)]
        public CSLSite.swNeuroOC.licenseStatusRequestBody Body;
        
        public licenseStatusRequest() {
        }
        
        public licenseStatusRequest(CSLSite.swNeuroOC.licenseStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class licenseStatusRequestBody {
        
        public licenseStatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class licenseStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="licenseStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSLSite.swNeuroOC.licenseStatusResponseBody Body;
        
        public licenseStatusResponse() {
        }
        
        public licenseStatusResponse(CSLSite.swNeuroOC.licenseStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class licenseStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string licenseStatusResult;
        
        public licenseStatusResponseBody() {
        }
        
        public licenseStatusResponseBody(string licenseStatusResult) {
            this.licenseStatusResult = licenseStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsNeuroSoapChannel : CSLSite.swNeuroOC.wsNeuroSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsNeuroSoapClient : System.ServiceModel.ClientBase<CSLSite.swNeuroOC.wsNeuroSoap>, CSLSite.swNeuroOC.wsNeuroSoap {
        
        public wsNeuroSoapClient() {
        }
        
        public wsNeuroSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsNeuroSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsNeuroSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsNeuroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSLSite.swNeuroOC.imageToIcaoResponse CSLSite.swNeuroOC.wsNeuroSoap.imageToIcao(CSLSite.swNeuroOC.imageToIcaoRequest request) {
            return base.Channel.imageToIcao(request);
        }
        
        public string imageToIcao(string base64Input) {
            CSLSite.swNeuroOC.imageToIcaoRequest inValue = new CSLSite.swNeuroOC.imageToIcaoRequest();
            inValue.Body = new CSLSite.swNeuroOC.imageToIcaoRequestBody();
            inValue.Body.base64Input = base64Input;
            CSLSite.swNeuroOC.imageToIcaoResponse retVal = ((CSLSite.swNeuroOC.wsNeuroSoap)(this)).imageToIcao(inValue);
            return retVal.Body.imageToIcaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSLSite.swNeuroOC.imageToIcaoResponse> CSLSite.swNeuroOC.wsNeuroSoap.imageToIcaoAsync(CSLSite.swNeuroOC.imageToIcaoRequest request) {
            return base.Channel.imageToIcaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSLSite.swNeuroOC.imageToIcaoResponse> imageToIcaoAsync(string base64Input) {
            CSLSite.swNeuroOC.imageToIcaoRequest inValue = new CSLSite.swNeuroOC.imageToIcaoRequest();
            inValue.Body = new CSLSite.swNeuroOC.imageToIcaoRequestBody();
            inValue.Body.base64Input = base64Input;
            return ((CSLSite.swNeuroOC.wsNeuroSoap)(this)).imageToIcaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSLSite.swNeuroOC.imageToTemplateResponse CSLSite.swNeuroOC.wsNeuroSoap.imageToTemplate(CSLSite.swNeuroOC.imageToTemplateRequest request) {
            return base.Channel.imageToTemplate(request);
        }
        
        public string imageToTemplate(string base64Input) {
            CSLSite.swNeuroOC.imageToTemplateRequest inValue = new CSLSite.swNeuroOC.imageToTemplateRequest();
            inValue.Body = new CSLSite.swNeuroOC.imageToTemplateRequestBody();
            inValue.Body.base64Input = base64Input;
            CSLSite.swNeuroOC.imageToTemplateResponse retVal = ((CSLSite.swNeuroOC.wsNeuroSoap)(this)).imageToTemplate(inValue);
            return retVal.Body.imageToTemplateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSLSite.swNeuroOC.imageToTemplateResponse> CSLSite.swNeuroOC.wsNeuroSoap.imageToTemplateAsync(CSLSite.swNeuroOC.imageToTemplateRequest request) {
            return base.Channel.imageToTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSLSite.swNeuroOC.imageToTemplateResponse> imageToTemplateAsync(string base64Input) {
            CSLSite.swNeuroOC.imageToTemplateRequest inValue = new CSLSite.swNeuroOC.imageToTemplateRequest();
            inValue.Body = new CSLSite.swNeuroOC.imageToTemplateRequestBody();
            inValue.Body.base64Input = base64Input;
            return ((CSLSite.swNeuroOC.wsNeuroSoap)(this)).imageToTemplateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSLSite.swNeuroOC.VerifyImageResponse CSLSite.swNeuroOC.wsNeuroSoap.VerifyImage(CSLSite.swNeuroOC.VerifyImageRequest request) {
            return base.Channel.VerifyImage(request);
        }
        
        public string VerifyImage(string base64Input1, string base64Input2) {
            CSLSite.swNeuroOC.VerifyImageRequest inValue = new CSLSite.swNeuroOC.VerifyImageRequest();
            inValue.Body = new CSLSite.swNeuroOC.VerifyImageRequestBody();
            inValue.Body.base64Input1 = base64Input1;
            inValue.Body.base64Input2 = base64Input2;
            CSLSite.swNeuroOC.VerifyImageResponse retVal = ((CSLSite.swNeuroOC.wsNeuroSoap)(this)).VerifyImage(inValue);
            return retVal.Body.VerifyImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSLSite.swNeuroOC.VerifyImageResponse> CSLSite.swNeuroOC.wsNeuroSoap.VerifyImageAsync(CSLSite.swNeuroOC.VerifyImageRequest request) {
            return base.Channel.VerifyImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSLSite.swNeuroOC.VerifyImageResponse> VerifyImageAsync(string base64Input1, string base64Input2) {
            CSLSite.swNeuroOC.VerifyImageRequest inValue = new CSLSite.swNeuroOC.VerifyImageRequest();
            inValue.Body = new CSLSite.swNeuroOC.VerifyImageRequestBody();
            inValue.Body.base64Input1 = base64Input1;
            inValue.Body.base64Input2 = base64Input2;
            return ((CSLSite.swNeuroOC.wsNeuroSoap)(this)).VerifyImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSLSite.swNeuroOC.VerifyTemplateResponse CSLSite.swNeuroOC.wsNeuroSoap.VerifyTemplate(CSLSite.swNeuroOC.VerifyTemplateRequest request) {
            return base.Channel.VerifyTemplate(request);
        }
        
        public string VerifyTemplate(string base64Input1, string base64Input2) {
            CSLSite.swNeuroOC.VerifyTemplateRequest inValue = new CSLSite.swNeuroOC.VerifyTemplateRequest();
            inValue.Body = new CSLSite.swNeuroOC.VerifyTemplateRequestBody();
            inValue.Body.base64Input1 = base64Input1;
            inValue.Body.base64Input2 = base64Input2;
            CSLSite.swNeuroOC.VerifyTemplateResponse retVal = ((CSLSite.swNeuroOC.wsNeuroSoap)(this)).VerifyTemplate(inValue);
            return retVal.Body.VerifyTemplateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSLSite.swNeuroOC.VerifyTemplateResponse> CSLSite.swNeuroOC.wsNeuroSoap.VerifyTemplateAsync(CSLSite.swNeuroOC.VerifyTemplateRequest request) {
            return base.Channel.VerifyTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSLSite.swNeuroOC.VerifyTemplateResponse> VerifyTemplateAsync(string base64Input1, string base64Input2) {
            CSLSite.swNeuroOC.VerifyTemplateRequest inValue = new CSLSite.swNeuroOC.VerifyTemplateRequest();
            inValue.Body = new CSLSite.swNeuroOC.VerifyTemplateRequestBody();
            inValue.Body.base64Input1 = base64Input1;
            inValue.Body.base64Input2 = base64Input2;
            return ((CSLSite.swNeuroOC.wsNeuroSoap)(this)).VerifyTemplateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSLSite.swNeuroOC.licenseStatusResponse CSLSite.swNeuroOC.wsNeuroSoap.licenseStatus(CSLSite.swNeuroOC.licenseStatusRequest request) {
            return base.Channel.licenseStatus(request);
        }
        
        public string licenseStatus() {
            CSLSite.swNeuroOC.licenseStatusRequest inValue = new CSLSite.swNeuroOC.licenseStatusRequest();
            inValue.Body = new CSLSite.swNeuroOC.licenseStatusRequestBody();
            CSLSite.swNeuroOC.licenseStatusResponse retVal = ((CSLSite.swNeuroOC.wsNeuroSoap)(this)).licenseStatus(inValue);
            return retVal.Body.licenseStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSLSite.swNeuroOC.licenseStatusResponse> CSLSite.swNeuroOC.wsNeuroSoap.licenseStatusAsync(CSLSite.swNeuroOC.licenseStatusRequest request) {
            return base.Channel.licenseStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSLSite.swNeuroOC.licenseStatusResponse> licenseStatusAsync() {
            CSLSite.swNeuroOC.licenseStatusRequest inValue = new CSLSite.swNeuroOC.licenseStatusRequest();
            inValue.Body = new CSLSite.swNeuroOC.licenseStatusRequestBody();
            return ((CSLSite.swNeuroOC.wsNeuroSoap)(this)).licenseStatusAsync(inValue);
        }
    }
}
