//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ecuapassModel", "FK_ECU_LIQUIDACION_PAGO_SENAE_FK", "ECU_LIQUIDACION_SENAE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ServicioEcuapass.AccesoDatos.ECU_LIQUIDACION_SENAE), "ECU_LIQUIDACION_PAGO_SENAE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ServicioEcuapass.AccesoDatos.ECU_LIQUIDACION_PAGO_SENAE), true)]

#endregion

namespace ServicioEcuapass.AccesoDatos
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ecuapassEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ecuapassEntities object using the connection string found in the 'ecuapassEntities' section of the application configuration file.
        /// </summary>
        public ecuapassEntities() : base("name=ecuapassEntities", "ecuapassEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ecuapassEntities object.
        /// </summary>
        public ecuapassEntities(string connectionString) : base(connectionString, "ecuapassEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ecuapassEntities object.
        /// </summary>
        public ecuapassEntities(EntityConnection connection) : base(connection, "ecuapassEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ECU_LIQUIDACION_SENAE> ECU_LIQUIDACION_SENAE
        {
            get
            {
                if ((_ECU_LIQUIDACION_SENAE == null))
                {
                    _ECU_LIQUIDACION_SENAE = base.CreateObjectSet<ECU_LIQUIDACION_SENAE>("ECU_LIQUIDACION_SENAE");
                }
                return _ECU_LIQUIDACION_SENAE;
            }
        }
        private ObjectSet<ECU_LIQUIDACION_SENAE> _ECU_LIQUIDACION_SENAE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ECU_LIQUIDACION_PAGO_SENAE> ECU_LIQUIDACION_PAGO_SENAE
        {
            get
            {
                if ((_ECU_LIQUIDACION_PAGO_SENAE == null))
                {
                    _ECU_LIQUIDACION_PAGO_SENAE = base.CreateObjectSet<ECU_LIQUIDACION_PAGO_SENAE>("ECU_LIQUIDACION_PAGO_SENAE");
                }
                return _ECU_LIQUIDACION_PAGO_SENAE;
            }
        }
        private ObjectSet<ECU_LIQUIDACION_PAGO_SENAE> _ECU_LIQUIDACION_PAGO_SENAE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ECU_CONSULTAS_ESTADO_FACTURA> ECU_CONSULTAS_ESTADO_FACTURAS
        {
            get
            {
                if ((_ECU_CONSULTAS_ESTADO_FACTURAS == null))
                {
                    _ECU_CONSULTAS_ESTADO_FACTURAS = base.CreateObjectSet<ECU_CONSULTAS_ESTADO_FACTURA>("ECU_CONSULTAS_ESTADO_FACTURAS");
                }
                return _ECU_CONSULTAS_ESTADO_FACTURAS;
            }
        }
        private ObjectSet<ECU_CONSULTAS_ESTADO_FACTURA> _ECU_CONSULTAS_ESTADO_FACTURAS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ECU_LIQUIDACION_ESTADO> ECU_LIQUIDACION_ESTADO
        {
            get
            {
                if ((_ECU_LIQUIDACION_ESTADO == null))
                {
                    _ECU_LIQUIDACION_ESTADO = base.CreateObjectSet<ECU_LIQUIDACION_ESTADO>("ECU_LIQUIDACION_ESTADO");
                }
                return _ECU_LIQUIDACION_ESTADO;
            }
        }
        private ObjectSet<ECU_LIQUIDACION_ESTADO> _ECU_LIQUIDACION_ESTADO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ECU_LIQUIDACION_LOG_WCF> ECU_LIQUIDACION_LOGS_WCF
        {
            get
            {
                if ((_ECU_LIQUIDACION_LOGS_WCF == null))
                {
                    _ECU_LIQUIDACION_LOGS_WCF = base.CreateObjectSet<ECU_LIQUIDACION_LOG_WCF>("ECU_LIQUIDACION_LOGS_WCF");
                }
                return _ECU_LIQUIDACION_LOGS_WCF;
            }
        }
        private ObjectSet<ECU_LIQUIDACION_LOG_WCF> _ECU_LIQUIDACION_LOGS_WCF;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ECU_LIQUIDACION_BANCOS> ECU_LIQUIDACION_BANCOS
        {
            get
            {
                if ((_ECU_LIQUIDACION_BANCOS == null))
                {
                    _ECU_LIQUIDACION_BANCOS = base.CreateObjectSet<ECU_LIQUIDACION_BANCOS>("ECU_LIQUIDACION_BANCOS");
                }
                return _ECU_LIQUIDACION_BANCOS;
            }
        }
        private ObjectSet<ECU_LIQUIDACION_BANCOS> _ECU_LIQUIDACION_BANCOS;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ECU_LIQUIDACION_SENAE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToECU_LIQUIDACION_SENAE(ECU_LIQUIDACION_SENAE eCU_LIQUIDACION_SENAE)
        {
            base.AddObject("ECU_LIQUIDACION_SENAE", eCU_LIQUIDACION_SENAE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ECU_LIQUIDACION_PAGO_SENAE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToECU_LIQUIDACION_PAGO_SENAE(ECU_LIQUIDACION_PAGO_SENAE eCU_LIQUIDACION_PAGO_SENAE)
        {
            base.AddObject("ECU_LIQUIDACION_PAGO_SENAE", eCU_LIQUIDACION_PAGO_SENAE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ECU_CONSULTAS_ESTADO_FACTURAS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToECU_CONSULTAS_ESTADO_FACTURAS(ECU_CONSULTAS_ESTADO_FACTURA eCU_CONSULTAS_ESTADO_FACTURA)
        {
            base.AddObject("ECU_CONSULTAS_ESTADO_FACTURAS", eCU_CONSULTAS_ESTADO_FACTURA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ECU_LIQUIDACION_ESTADO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToECU_LIQUIDACION_ESTADO(ECU_LIQUIDACION_ESTADO eCU_LIQUIDACION_ESTADO)
        {
            base.AddObject("ECU_LIQUIDACION_ESTADO", eCU_LIQUIDACION_ESTADO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ECU_LIQUIDACION_LOGS_WCF EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToECU_LIQUIDACION_LOGS_WCF(ECU_LIQUIDACION_LOG_WCF eCU_LIQUIDACION_LOG_WCF)
        {
            base.AddObject("ECU_LIQUIDACION_LOGS_WCF", eCU_LIQUIDACION_LOG_WCF);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ECU_LIQUIDACION_BANCOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToECU_LIQUIDACION_BANCOS(ECU_LIQUIDACION_BANCOS eCU_LIQUIDACION_BANCOS)
        {
            base.AddObject("ECU_LIQUIDACION_BANCOS", eCU_LIQUIDACION_BANCOS);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="codigoPago">No Metadata Documentation available.</param>
        /// <param name="numeroLiquidacion">No Metadata Documentation available.</param>
        /// <param name="monto">No Metadata Documentation available.</param>
        /// <param name="canal">No Metadata Documentation available.</param>
        /// <param name="banco">No Metadata Documentation available.</param>
        /// <param name="fechaRecaudacion">No Metadata Documentation available.</param>
        /// <param name="codigoAceptacionPago">No Metadata Documentation available.</param>
        /// <param name="fechaContable">No Metadata Documentation available.</param>
        /// <param name="tipoTransaccion">No Metadata Documentation available.</param>
        /// <param name="customer">No Metadata Documentation available.</param>
        /// <param name="ruc">No Metadata Documentation available.</param>
        public int IngresoPago(global::System.String codigoPago, global::System.String numeroLiquidacion, Nullable<global::System.Decimal> monto, global::System.String canal, global::System.String banco, Nullable<global::System.DateTime> fechaRecaudacion, global::System.String codigoAceptacionPago, Nullable<global::System.DateTime> fechaContable, global::System.String tipoTransaccion, global::System.String customer, global::System.String ruc)
        {
            ObjectParameter codigoPagoParameter;
            if (codigoPago != null)
            {
                codigoPagoParameter = new ObjectParameter("codigoPago", codigoPago);
            }
            else
            {
                codigoPagoParameter = new ObjectParameter("codigoPago", typeof(global::System.String));
            }
    
            ObjectParameter numeroLiquidacionParameter;
            if (numeroLiquidacion != null)
            {
                numeroLiquidacionParameter = new ObjectParameter("numeroLiquidacion", numeroLiquidacion);
            }
            else
            {
                numeroLiquidacionParameter = new ObjectParameter("numeroLiquidacion", typeof(global::System.String));
            }
    
            ObjectParameter montoParameter;
            if (monto.HasValue)
            {
                montoParameter = new ObjectParameter("monto", monto);
            }
            else
            {
                montoParameter = new ObjectParameter("monto", typeof(global::System.Decimal));
            }
    
            ObjectParameter canalParameter;
            if (canal != null)
            {
                canalParameter = new ObjectParameter("canal", canal);
            }
            else
            {
                canalParameter = new ObjectParameter("canal", typeof(global::System.String));
            }
    
            ObjectParameter bancoParameter;
            if (banco != null)
            {
                bancoParameter = new ObjectParameter("banco", banco);
            }
            else
            {
                bancoParameter = new ObjectParameter("banco", typeof(global::System.String));
            }
    
            ObjectParameter fechaRecaudacionParameter;
            if (fechaRecaudacion.HasValue)
            {
                fechaRecaudacionParameter = new ObjectParameter("fechaRecaudacion", fechaRecaudacion);
            }
            else
            {
                fechaRecaudacionParameter = new ObjectParameter("fechaRecaudacion", typeof(global::System.DateTime));
            }
    
            ObjectParameter codigoAceptacionPagoParameter;
            if (codigoAceptacionPago != null)
            {
                codigoAceptacionPagoParameter = new ObjectParameter("codigoAceptacionPago", codigoAceptacionPago);
            }
            else
            {
                codigoAceptacionPagoParameter = new ObjectParameter("codigoAceptacionPago", typeof(global::System.String));
            }
    
            ObjectParameter fechaContableParameter;
            if (fechaContable.HasValue)
            {
                fechaContableParameter = new ObjectParameter("fechaContable", fechaContable);
            }
            else
            {
                fechaContableParameter = new ObjectParameter("fechaContable", typeof(global::System.DateTime));
            }
    
            ObjectParameter tipoTransaccionParameter;
            if (tipoTransaccion != null)
            {
                tipoTransaccionParameter = new ObjectParameter("TipoTransaccion", tipoTransaccion);
            }
            else
            {
                tipoTransaccionParameter = new ObjectParameter("TipoTransaccion", typeof(global::System.String));
            }
    
            ObjectParameter customerParameter;
            if (customer != null)
            {
                customerParameter = new ObjectParameter("customer", customer);
            }
            else
            {
                customerParameter = new ObjectParameter("customer", typeof(global::System.String));
            }
    
            ObjectParameter rucParameter;
            if (ruc != null)
            {
                rucParameter = new ObjectParameter("ruc", ruc);
            }
            else
            {
                rucParameter = new ObjectParameter("ruc", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("IngresoPago", codigoPagoParameter, numeroLiquidacionParameter, montoParameter, canalParameter, bancoParameter, fechaRecaudacionParameter, codigoAceptacionPagoParameter, fechaContableParameter, tipoTransaccionParameter, customerParameter, rucParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ecuapassModel", Name="ECU_CONSULTAS_ESTADO_FACTURA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ECU_CONSULTAS_ESTADO_FACTURA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ECU_CONSULTAS_ESTADO_FACTURA object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nUMERO_LIQUIDACION">Initial value of the NUMERO_LIQUIDACION property.</param>
        /// <param name="vALOR_FACTURA">Initial value of the VALOR_FACTURA property.</param>
        /// <param name="vALOR_PAGADO">Initial value of the VALOR_PAGADO property.</param>
        /// <param name="vALOR_PENDIENTE">Initial value of the VALOR_PENDIENTE property.</param>
        /// <param name="fECHA">Initial value of the FECHA property.</param>
        /// <param name="uSUARIO">Initial value of the USUARIO property.</param>
        /// <param name="fUE_OK">Initial value of the FUE_OK property.</param>
        /// <param name="mENSAJE">Initial value of the MENSAJE property.</param>
        public static ECU_CONSULTAS_ESTADO_FACTURA CreateECU_CONSULTAS_ESTADO_FACTURA(global::System.Int64 id, global::System.String nUMERO_LIQUIDACION, global::System.Decimal vALOR_FACTURA, global::System.Decimal vALOR_PAGADO, global::System.Decimal vALOR_PENDIENTE, global::System.DateTime fECHA, global::System.String uSUARIO, global::System.Boolean fUE_OK, global::System.String mENSAJE)
        {
            ECU_CONSULTAS_ESTADO_FACTURA eCU_CONSULTAS_ESTADO_FACTURA = new ECU_CONSULTAS_ESTADO_FACTURA();
            eCU_CONSULTAS_ESTADO_FACTURA.ID = id;
            eCU_CONSULTAS_ESTADO_FACTURA.NUMERO_LIQUIDACION = nUMERO_LIQUIDACION;
            eCU_CONSULTAS_ESTADO_FACTURA.VALOR_FACTURA = vALOR_FACTURA;
            eCU_CONSULTAS_ESTADO_FACTURA.VALOR_PAGADO = vALOR_PAGADO;
            eCU_CONSULTAS_ESTADO_FACTURA.VALOR_PENDIENTE = vALOR_PENDIENTE;
            eCU_CONSULTAS_ESTADO_FACTURA.FECHA = fECHA;
            eCU_CONSULTAS_ESTADO_FACTURA.USUARIO = uSUARIO;
            eCU_CONSULTAS_ESTADO_FACTURA.FUE_OK = fUE_OK;
            eCU_CONSULTAS_ESTADO_FACTURA.MENSAJE = mENSAJE;
            return eCU_CONSULTAS_ESTADO_FACTURA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NUMERO_LIQUIDACION
        {
            get
            {
                return _NUMERO_LIQUIDACION;
            }
            set
            {
                OnNUMERO_LIQUIDACIONChanging(value);
                ReportPropertyChanging("NUMERO_LIQUIDACION");
                _NUMERO_LIQUIDACION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NUMERO_LIQUIDACION");
                OnNUMERO_LIQUIDACIONChanged();
            }
        }
        private global::System.String _NUMERO_LIQUIDACION;
        partial void OnNUMERO_LIQUIDACIONChanging(global::System.String value);
        partial void OnNUMERO_LIQUIDACIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal VALOR_FACTURA
        {
            get
            {
                return _VALOR_FACTURA;
            }
            set
            {
                OnVALOR_FACTURAChanging(value);
                ReportPropertyChanging("VALOR_FACTURA");
                _VALOR_FACTURA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALOR_FACTURA");
                OnVALOR_FACTURAChanged();
            }
        }
        private global::System.Decimal _VALOR_FACTURA;
        partial void OnVALOR_FACTURAChanging(global::System.Decimal value);
        partial void OnVALOR_FACTURAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal VALOR_PAGADO
        {
            get
            {
                return _VALOR_PAGADO;
            }
            set
            {
                OnVALOR_PAGADOChanging(value);
                ReportPropertyChanging("VALOR_PAGADO");
                _VALOR_PAGADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALOR_PAGADO");
                OnVALOR_PAGADOChanged();
            }
        }
        private global::System.Decimal _VALOR_PAGADO;
        partial void OnVALOR_PAGADOChanging(global::System.Decimal value);
        partial void OnVALOR_PAGADOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal VALOR_PENDIENTE
        {
            get
            {
                return _VALOR_PENDIENTE;
            }
            set
            {
                OnVALOR_PENDIENTEChanging(value);
                ReportPropertyChanging("VALOR_PENDIENTE");
                _VALOR_PENDIENTE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALOR_PENDIENTE");
                OnVALOR_PENDIENTEChanged();
            }
        }
        private global::System.Decimal _VALOR_PENDIENTE;
        partial void OnVALOR_PENDIENTEChanging(global::System.Decimal value);
        partial void OnVALOR_PENDIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA
        {
            get
            {
                return _FECHA;
            }
            set
            {
                OnFECHAChanging(value);
                ReportPropertyChanging("FECHA");
                _FECHA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA");
                OnFECHAChanged();
            }
        }
        private global::System.DateTime _FECHA;
        partial void OnFECHAChanging(global::System.DateTime value);
        partial void OnFECHAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USUARIO
        {
            get
            {
                return _USUARIO;
            }
            set
            {
                OnUSUARIOChanging(value);
                ReportPropertyChanging("USUARIO");
                _USUARIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USUARIO");
                OnUSUARIOChanged();
            }
        }
        private global::System.String _USUARIO;
        partial void OnUSUARIOChanging(global::System.String value);
        partial void OnUSUARIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FUE_OK
        {
            get
            {
                return _FUE_OK;
            }
            set
            {
                OnFUE_OKChanging(value);
                ReportPropertyChanging("FUE_OK");
                _FUE_OK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FUE_OK");
                OnFUE_OKChanged();
            }
        }
        private global::System.Boolean _FUE_OK;
        partial void OnFUE_OKChanging(global::System.Boolean value);
        partial void OnFUE_OKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MENSAJE
        {
            get
            {
                return _MENSAJE;
            }
            set
            {
                OnMENSAJEChanging(value);
                ReportPropertyChanging("MENSAJE");
                _MENSAJE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MENSAJE");
                OnMENSAJEChanged();
            }
        }
        private global::System.String _MENSAJE;
        partial void OnMENSAJEChanging(global::System.String value);
        partial void OnMENSAJEChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ecuapassModel", Name="ECU_LIQUIDACION_BANCOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ECU_LIQUIDACION_BANCOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ECU_LIQUIDACION_BANCOS object.
        /// </summary>
        /// <param name="bANCO_SYSPRO">Initial value of the BANCO_SYSPRO property.</param>
        /// <param name="bANCO_SENAE">Initial value of the BANCO_SENAE property.</param>
        public static ECU_LIQUIDACION_BANCOS CreateECU_LIQUIDACION_BANCOS(global::System.String bANCO_SYSPRO, global::System.String bANCO_SENAE)
        {
            ECU_LIQUIDACION_BANCOS eCU_LIQUIDACION_BANCOS = new ECU_LIQUIDACION_BANCOS();
            eCU_LIQUIDACION_BANCOS.BANCO_SYSPRO = bANCO_SYSPRO;
            eCU_LIQUIDACION_BANCOS.BANCO_SENAE = bANCO_SENAE;
            return eCU_LIQUIDACION_BANCOS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BANCO_SYSPRO
        {
            get
            {
                return _BANCO_SYSPRO;
            }
            set
            {
                if (_BANCO_SYSPRO != value)
                {
                    OnBANCO_SYSPROChanging(value);
                    ReportPropertyChanging("BANCO_SYSPRO");
                    _BANCO_SYSPRO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("BANCO_SYSPRO");
                    OnBANCO_SYSPROChanged();
                }
            }
        }
        private global::System.String _BANCO_SYSPRO;
        partial void OnBANCO_SYSPROChanging(global::System.String value);
        partial void OnBANCO_SYSPROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BANCO_SENAE
        {
            get
            {
                return _BANCO_SENAE;
            }
            set
            {
                OnBANCO_SENAEChanging(value);
                ReportPropertyChanging("BANCO_SENAE");
                _BANCO_SENAE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BANCO_SENAE");
                OnBANCO_SENAEChanged();
            }
        }
        private global::System.String _BANCO_SENAE;
        partial void OnBANCO_SENAEChanging(global::System.String value);
        partial void OnBANCO_SENAEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SAP_GL_CODE
        {
            get
            {
                return _SAP_GL_CODE;
            }
            set
            {
                OnSAP_GL_CODEChanging(value);
                ReportPropertyChanging("SAP_GL_CODE");
                _SAP_GL_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SAP_GL_CODE");
                OnSAP_GL_CODEChanged();
            }
        }
        private global::System.String _SAP_GL_CODE;
        partial void OnSAP_GL_CODEChanging(global::System.String value);
        partial void OnSAP_GL_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BANCO_BANRED
        {
            get
            {
                return _BANCO_BANRED;
            }
            set
            {
                OnBANCO_BANREDChanging(value);
                ReportPropertyChanging("BANCO_BANRED");
                _BANCO_BANRED = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BANCO_BANRED");
                OnBANCO_BANREDChanged();
            }
        }
        private global::System.String _BANCO_BANRED;
        partial void OnBANCO_BANREDChanging(global::System.String value);
        partial void OnBANCO_BANREDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ecuapassModel", Name="ECU_LIQUIDACION_ESTADO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ECU_LIQUIDACION_ESTADO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ECU_LIQUIDACION_ESTADO object.
        /// </summary>
        /// <param name="cODIGO_UNICO">Initial value of the CODIGO_UNICO property.</param>
        /// <param name="nUMERO_LIQUIDACION">Initial value of the NUMERO_LIQUIDACION property.</param>
        /// <param name="eSTADO">Initial value of the ESTADO property.</param>
        /// <param name="uSUARIO">Initial value of the USUARIO property.</param>
        /// <param name="fECHA">Initial value of the FECHA property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static ECU_LIQUIDACION_ESTADO CreateECU_LIQUIDACION_ESTADO(global::System.Int64 cODIGO_UNICO, global::System.String nUMERO_LIQUIDACION, global::System.String eSTADO, global::System.String uSUARIO, global::System.DateTime fECHA, global::System.Int64 id)
        {
            ECU_LIQUIDACION_ESTADO eCU_LIQUIDACION_ESTADO = new ECU_LIQUIDACION_ESTADO();
            eCU_LIQUIDACION_ESTADO.CODIGO_UNICO = cODIGO_UNICO;
            eCU_LIQUIDACION_ESTADO.NUMERO_LIQUIDACION = nUMERO_LIQUIDACION;
            eCU_LIQUIDACION_ESTADO.ESTADO = eSTADO;
            eCU_LIQUIDACION_ESTADO.USUARIO = uSUARIO;
            eCU_LIQUIDACION_ESTADO.FECHA = fECHA;
            eCU_LIQUIDACION_ESTADO.ID = id;
            return eCU_LIQUIDACION_ESTADO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CODIGO_UNICO
        {
            get
            {
                return _CODIGO_UNICO;
            }
            set
            {
                OnCODIGO_UNICOChanging(value);
                ReportPropertyChanging("CODIGO_UNICO");
                _CODIGO_UNICO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CODIGO_UNICO");
                OnCODIGO_UNICOChanged();
            }
        }
        private global::System.Int64 _CODIGO_UNICO;
        partial void OnCODIGO_UNICOChanging(global::System.Int64 value);
        partial void OnCODIGO_UNICOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NUMERO_LIQUIDACION
        {
            get
            {
                return _NUMERO_LIQUIDACION;
            }
            set
            {
                OnNUMERO_LIQUIDACIONChanging(value);
                ReportPropertyChanging("NUMERO_LIQUIDACION");
                _NUMERO_LIQUIDACION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NUMERO_LIQUIDACION");
                OnNUMERO_LIQUIDACIONChanged();
            }
        }
        private global::System.String _NUMERO_LIQUIDACION;
        partial void OnNUMERO_LIQUIDACIONChanging(global::System.String value);
        partial void OnNUMERO_LIQUIDACIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESTADO
        {
            get
            {
                return _ESTADO;
            }
            set
            {
                OnESTADOChanging(value);
                ReportPropertyChanging("ESTADO");
                _ESTADO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ESTADO");
                OnESTADOChanged();
            }
        }
        private global::System.String _ESTADO;
        partial void OnESTADOChanging(global::System.String value);
        partial void OnESTADOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USUARIO
        {
            get
            {
                return _USUARIO;
            }
            set
            {
                OnUSUARIOChanging(value);
                ReportPropertyChanging("USUARIO");
                _USUARIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USUARIO");
                OnUSUARIOChanged();
            }
        }
        private global::System.String _USUARIO;
        partial void OnUSUARIOChanging(global::System.String value);
        partial void OnUSUARIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA
        {
            get
            {
                return _FECHA;
            }
            set
            {
                OnFECHAChanging(value);
                ReportPropertyChanging("FECHA");
                _FECHA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA");
                OnFECHAChanged();
            }
        }
        private global::System.DateTime _FECHA;
        partial void OnFECHAChanging(global::System.DateTime value);
        partial void OnFECHAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ecuapassModel", Name="ECU_LIQUIDACION_LOG_WCF")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ECU_LIQUIDACION_LOG_WCF : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ECU_LIQUIDACION_LOG_WCF object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="fECHA">Initial value of the FECHA property.</param>
        /// <param name="mENSAJE">Initial value of the MENSAJE property.</param>
        /// <param name="dETALLE">Initial value of the DETALLE property.</param>
        /// <param name="eS_SERVICIO_ADUANA">Initial value of the ES_SERVICIO_ADUANA property.</param>
        /// <param name="uSUARIO">Initial value of the USUARIO property.</param>
        public static ECU_LIQUIDACION_LOG_WCF CreateECU_LIQUIDACION_LOG_WCF(global::System.Int32 id, global::System.DateTime fECHA, global::System.String mENSAJE, global::System.String dETALLE, global::System.Boolean eS_SERVICIO_ADUANA, global::System.String uSUARIO)
        {
            ECU_LIQUIDACION_LOG_WCF eCU_LIQUIDACION_LOG_WCF = new ECU_LIQUIDACION_LOG_WCF();
            eCU_LIQUIDACION_LOG_WCF.ID = id;
            eCU_LIQUIDACION_LOG_WCF.FECHA = fECHA;
            eCU_LIQUIDACION_LOG_WCF.MENSAJE = mENSAJE;
            eCU_LIQUIDACION_LOG_WCF.DETALLE = dETALLE;
            eCU_LIQUIDACION_LOG_WCF.ES_SERVICIO_ADUANA = eS_SERVICIO_ADUANA;
            eCU_LIQUIDACION_LOG_WCF.USUARIO = uSUARIO;
            return eCU_LIQUIDACION_LOG_WCF;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA
        {
            get
            {
                return _FECHA;
            }
            set
            {
                OnFECHAChanging(value);
                ReportPropertyChanging("FECHA");
                _FECHA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA");
                OnFECHAChanged();
            }
        }
        private global::System.DateTime _FECHA;
        partial void OnFECHAChanging(global::System.DateTime value);
        partial void OnFECHAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MENSAJE
        {
            get
            {
                return _MENSAJE;
            }
            set
            {
                OnMENSAJEChanging(value);
                ReportPropertyChanging("MENSAJE");
                _MENSAJE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MENSAJE");
                OnMENSAJEChanged();
            }
        }
        private global::System.String _MENSAJE;
        partial void OnMENSAJEChanging(global::System.String value);
        partial void OnMENSAJEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DETALLE
        {
            get
            {
                return _DETALLE;
            }
            set
            {
                OnDETALLEChanging(value);
                ReportPropertyChanging("DETALLE");
                _DETALLE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DETALLE");
                OnDETALLEChanged();
            }
        }
        private global::System.String _DETALLE;
        partial void OnDETALLEChanging(global::System.String value);
        partial void OnDETALLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ES_SERVICIO_ADUANA
        {
            get
            {
                return _ES_SERVICIO_ADUANA;
            }
            set
            {
                OnES_SERVICIO_ADUANAChanging(value);
                ReportPropertyChanging("ES_SERVICIO_ADUANA");
                _ES_SERVICIO_ADUANA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ES_SERVICIO_ADUANA");
                OnES_SERVICIO_ADUANAChanged();
            }
        }
        private global::System.Boolean _ES_SERVICIO_ADUANA;
        partial void OnES_SERVICIO_ADUANAChanging(global::System.Boolean value);
        partial void OnES_SERVICIO_ADUANAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USUARIO
        {
            get
            {
                return _USUARIO;
            }
            set
            {
                OnUSUARIOChanging(value);
                ReportPropertyChanging("USUARIO");
                _USUARIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USUARIO");
                OnUSUARIOChanged();
            }
        }
        private global::System.String _USUARIO;
        partial void OnUSUARIOChanging(global::System.String value);
        partial void OnUSUARIOChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ecuapassModel", Name="ECU_LIQUIDACION_PAGO_SENAE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ECU_LIQUIDACION_PAGO_SENAE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ECU_LIQUIDACION_PAGO_SENAE object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="eSTADO">Initial value of the ESTADO property.</param>
        /// <param name="cODIGO_FACTURA">Initial value of the CODIGO_FACTURA property.</param>
        /// <param name="cANAL_RECAUDO">Initial value of the CANAL_RECAUDO property.</param>
        /// <param name="bANCO_PAGO">Initial value of the BANCO_PAGO property.</param>
        /// <param name="fECHA_RECAUDACION">Initial value of the FECHA_RECAUDACION property.</param>
        /// <param name="cODIGO_PAGO">Initial value of the CODIGO_PAGO property.</param>
        /// <param name="cODIGO_ACEPTACION_PAGO">Initial value of the CODIGO_ACEPTACION_PAGO property.</param>
        /// <param name="fECHA_CONTABLE">Initial value of the FECHA_CONTABLE property.</param>
        /// <param name="fECHA_REGISTRO">Initial value of the FECHA_REGISTRO property.</param>
        public static ECU_LIQUIDACION_PAGO_SENAE CreateECU_LIQUIDACION_PAGO_SENAE(global::System.Int32 id, global::System.String eSTADO, global::System.Int64 cODIGO_FACTURA, global::System.String cANAL_RECAUDO, global::System.String bANCO_PAGO, global::System.DateTime fECHA_RECAUDACION, global::System.String cODIGO_PAGO, global::System.String cODIGO_ACEPTACION_PAGO, global::System.DateTime fECHA_CONTABLE, global::System.DateTime fECHA_REGISTRO)
        {
            ECU_LIQUIDACION_PAGO_SENAE eCU_LIQUIDACION_PAGO_SENAE = new ECU_LIQUIDACION_PAGO_SENAE();
            eCU_LIQUIDACION_PAGO_SENAE.ID = id;
            eCU_LIQUIDACION_PAGO_SENAE.ESTADO = eSTADO;
            eCU_LIQUIDACION_PAGO_SENAE.CODIGO_FACTURA = cODIGO_FACTURA;
            eCU_LIQUIDACION_PAGO_SENAE.CANAL_RECAUDO = cANAL_RECAUDO;
            eCU_LIQUIDACION_PAGO_SENAE.BANCO_PAGO = bANCO_PAGO;
            eCU_LIQUIDACION_PAGO_SENAE.FECHA_RECAUDACION = fECHA_RECAUDACION;
            eCU_LIQUIDACION_PAGO_SENAE.CODIGO_PAGO = cODIGO_PAGO;
            eCU_LIQUIDACION_PAGO_SENAE.CODIGO_ACEPTACION_PAGO = cODIGO_ACEPTACION_PAGO;
            eCU_LIQUIDACION_PAGO_SENAE.FECHA_CONTABLE = fECHA_CONTABLE;
            eCU_LIQUIDACION_PAGO_SENAE.FECHA_REGISTRO = fECHA_REGISTRO;
            return eCU_LIQUIDACION_PAGO_SENAE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESTADO
        {
            get
            {
                return _ESTADO;
            }
            set
            {
                OnESTADOChanging(value);
                ReportPropertyChanging("ESTADO");
                _ESTADO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ESTADO");
                OnESTADOChanged();
            }
        }
        private global::System.String _ESTADO;
        partial void OnESTADOChanging(global::System.String value);
        partial void OnESTADOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CODIGO_FACTURA
        {
            get
            {
                return _CODIGO_FACTURA;
            }
            set
            {
                OnCODIGO_FACTURAChanging(value);
                ReportPropertyChanging("CODIGO_FACTURA");
                _CODIGO_FACTURA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CODIGO_FACTURA");
                OnCODIGO_FACTURAChanged();
            }
        }
        private global::System.Int64 _CODIGO_FACTURA;
        partial void OnCODIGO_FACTURAChanging(global::System.Int64 value);
        partial void OnCODIGO_FACTURAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTO_RECAUDADO
        {
            get
            {
                return _MONTO_RECAUDADO;
            }
            set
            {
                OnMONTO_RECAUDADOChanging(value);
                ReportPropertyChanging("MONTO_RECAUDADO");
                _MONTO_RECAUDADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTO_RECAUDADO");
                OnMONTO_RECAUDADOChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTO_RECAUDADO;
        partial void OnMONTO_RECAUDADOChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTO_RECAUDADOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CANAL_RECAUDO
        {
            get
            {
                return _CANAL_RECAUDO;
            }
            set
            {
                OnCANAL_RECAUDOChanging(value);
                ReportPropertyChanging("CANAL_RECAUDO");
                _CANAL_RECAUDO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CANAL_RECAUDO");
                OnCANAL_RECAUDOChanged();
            }
        }
        private global::System.String _CANAL_RECAUDO;
        partial void OnCANAL_RECAUDOChanging(global::System.String value);
        partial void OnCANAL_RECAUDOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BANCO_PAGO
        {
            get
            {
                return _BANCO_PAGO;
            }
            set
            {
                OnBANCO_PAGOChanging(value);
                ReportPropertyChanging("BANCO_PAGO");
                _BANCO_PAGO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BANCO_PAGO");
                OnBANCO_PAGOChanged();
            }
        }
        private global::System.String _BANCO_PAGO;
        partial void OnBANCO_PAGOChanging(global::System.String value);
        partial void OnBANCO_PAGOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA_RECAUDACION
        {
            get
            {
                return _FECHA_RECAUDACION;
            }
            set
            {
                OnFECHA_RECAUDACIONChanging(value);
                ReportPropertyChanging("FECHA_RECAUDACION");
                _FECHA_RECAUDACION = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_RECAUDACION");
                OnFECHA_RECAUDACIONChanged();
            }
        }
        private global::System.DateTime _FECHA_RECAUDACION;
        partial void OnFECHA_RECAUDACIONChanging(global::System.DateTime value);
        partial void OnFECHA_RECAUDACIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CODIGO_PAGO
        {
            get
            {
                return _CODIGO_PAGO;
            }
            set
            {
                OnCODIGO_PAGOChanging(value);
                ReportPropertyChanging("CODIGO_PAGO");
                _CODIGO_PAGO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CODIGO_PAGO");
                OnCODIGO_PAGOChanged();
            }
        }
        private global::System.String _CODIGO_PAGO;
        partial void OnCODIGO_PAGOChanging(global::System.String value);
        partial void OnCODIGO_PAGOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CODIGO_ACEPTACION_PAGO
        {
            get
            {
                return _CODIGO_ACEPTACION_PAGO;
            }
            set
            {
                OnCODIGO_ACEPTACION_PAGOChanging(value);
                ReportPropertyChanging("CODIGO_ACEPTACION_PAGO");
                _CODIGO_ACEPTACION_PAGO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CODIGO_ACEPTACION_PAGO");
                OnCODIGO_ACEPTACION_PAGOChanged();
            }
        }
        private global::System.String _CODIGO_ACEPTACION_PAGO;
        partial void OnCODIGO_ACEPTACION_PAGOChanging(global::System.String value);
        partial void OnCODIGO_ACEPTACION_PAGOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA_CONTABLE
        {
            get
            {
                return _FECHA_CONTABLE;
            }
            set
            {
                OnFECHA_CONTABLEChanging(value);
                ReportPropertyChanging("FECHA_CONTABLE");
                _FECHA_CONTABLE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_CONTABLE");
                OnFECHA_CONTABLEChanged();
            }
        }
        private global::System.DateTime _FECHA_CONTABLE;
        partial void OnFECHA_CONTABLEChanging(global::System.DateTime value);
        partial void OnFECHA_CONTABLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NUMERO_LIQUIDACION
        {
            get
            {
                return _NUMERO_LIQUIDACION;
            }
            set
            {
                OnNUMERO_LIQUIDACIONChanging(value);
                ReportPropertyChanging("NUMERO_LIQUIDACION");
                _NUMERO_LIQUIDACION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NUMERO_LIQUIDACION");
                OnNUMERO_LIQUIDACIONChanged();
            }
        }
        private global::System.String _NUMERO_LIQUIDACION;
        partial void OnNUMERO_LIQUIDACIONChanging(global::System.String value);
        partial void OnNUMERO_LIQUIDACIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TIPO_TRANSACCION
        {
            get
            {
                return _TIPO_TRANSACCION;
            }
            set
            {
                OnTIPO_TRANSACCIONChanging(value);
                ReportPropertyChanging("TIPO_TRANSACCION");
                _TIPO_TRANSACCION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TIPO_TRANSACCION");
                OnTIPO_TRANSACCIONChanged();
            }
        }
        private global::System.String _TIPO_TRANSACCION;
        partial void OnTIPO_TRANSACCIONChanging(global::System.String value);
        partial void OnTIPO_TRANSACCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MOTIVO_PAGO
        {
            get
            {
                return _MOTIVO_PAGO;
            }
            set
            {
                OnMOTIVO_PAGOChanging(value);
                ReportPropertyChanging("MOTIVO_PAGO");
                _MOTIVO_PAGO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MOTIVO_PAGO");
                OnMOTIVO_PAGOChanged();
            }
        }
        private global::System.String _MOTIVO_PAGO;
        partial void OnMOTIVO_PAGOChanging(global::System.String value);
        partial void OnMOTIVO_PAGOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA_REGISTRO
        {
            get
            {
                return _FECHA_REGISTRO;
            }
            set
            {
                OnFECHA_REGISTROChanging(value);
                ReportPropertyChanging("FECHA_REGISTRO");
                _FECHA_REGISTRO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_REGISTRO");
                OnFECHA_REGISTROChanged();
            }
        }
        private global::System.DateTime _FECHA_REGISTRO;
        partial void OnFECHA_REGISTROChanging(global::System.DateTime value);
        partial void OnFECHA_REGISTROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USUARIO_REGISTRO
        {
            get
            {
                return _USUARIO_REGISTRO;
            }
            set
            {
                OnUSUARIO_REGISTROChanging(value);
                ReportPropertyChanging("USUARIO_REGISTRO");
                _USUARIO_REGISTRO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USUARIO_REGISTRO");
                OnUSUARIO_REGISTROChanged();
            }
        }
        private global::System.String _USUARIO_REGISTRO;
        partial void OnUSUARIO_REGISTROChanging(global::System.String value);
        partial void OnUSUARIO_REGISTROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CODIGO_FACTURA_ANTICIPO
        {
            get
            {
                return _CODIGO_FACTURA_ANTICIPO;
            }
            set
            {
                OnCODIGO_FACTURA_ANTICIPOChanging(value);
                ReportPropertyChanging("CODIGO_FACTURA_ANTICIPO");
                _CODIGO_FACTURA_ANTICIPO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CODIGO_FACTURA_ANTICIPO");
                OnCODIGO_FACTURA_ANTICIPOChanged();
            }
        }
        private Nullable<global::System.Int64> _CODIGO_FACTURA_ANTICIPO;
        partial void OnCODIGO_FACTURA_ANTICIPOChanging(Nullable<global::System.Int64> value);
        partial void OnCODIGO_FACTURA_ANTICIPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String INVOICE
        {
            get
            {
                return _INVOICE;
            }
            set
            {
                OnINVOICEChanging(value);
                ReportPropertyChanging("INVOICE");
                _INVOICE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("INVOICE");
                OnINVOICEChanged();
            }
        }
        private global::System.String _INVOICE;
        partial void OnINVOICEChanging(global::System.String value);
        partial void OnINVOICEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUSTOMER
        {
            get
            {
                return _CUSTOMER;
            }
            set
            {
                OnCUSTOMERChanging(value);
                ReportPropertyChanging("CUSTOMER");
                _CUSTOMER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CUSTOMER");
                OnCUSTOMERChanged();
            }
        }
        private global::System.String _CUSTOMER;
        partial void OnCUSTOMERChanging(global::System.String value);
        partial void OnCUSTOMERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BANCO_SYSPRO
        {
            get
            {
                return _BANCO_SYSPRO;
            }
            set
            {
                OnBANCO_SYSPROChanging(value);
                ReportPropertyChanging("BANCO_SYSPRO");
                _BANCO_SYSPRO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BANCO_SYSPRO");
                OnBANCO_SYSPROChanged();
            }
        }
        private global::System.String _BANCO_SYSPRO;
        partial void OnBANCO_SYSPROChanging(global::System.String value);
        partial void OnBANCO_SYSPROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SYSPRO
        {
            get
            {
                return _SYSPRO;
            }
            set
            {
                OnSYSPROChanging(value);
                ReportPropertyChanging("SYSPRO");
                _SYSPRO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SYSPRO");
                OnSYSPROChanged();
            }
        }
        private global::System.String _SYSPRO;
        partial void OnSYSPROChanging(global::System.String value);
        partial void OnSYSPROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CODIGO_CLIENTE
        {
            get
            {
                return _CODIGO_CLIENTE;
            }
            set
            {
                OnCODIGO_CLIENTEChanging(value);
                ReportPropertyChanging("CODIGO_CLIENTE");
                _CODIGO_CLIENTE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CODIGO_CLIENTE");
                OnCODIGO_CLIENTEChanged();
            }
        }
        private global::System.String _CODIGO_CLIENTE;
        partial void OnCODIGO_CLIENTEChanging(global::System.String value);
        partial void OnCODIGO_CLIENTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SOCIEDAD_SAP
        {
            get
            {
                return _SOCIEDAD_SAP;
            }
            set
            {
                OnSOCIEDAD_SAPChanging(value);
                ReportPropertyChanging("SOCIEDAD_SAP");
                _SOCIEDAD_SAP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SOCIEDAD_SAP");
                OnSOCIEDAD_SAPChanged();
            }
        }
        private global::System.String _SOCIEDAD_SAP;
        partial void OnSOCIEDAD_SAPChanging(global::System.String value);
        partial void OnSOCIEDAD_SAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ESTADO_SAP
        {
            get
            {
                return _ESTADO_SAP;
            }
            set
            {
                OnESTADO_SAPChanging(value);
                ReportPropertyChanging("ESTADO_SAP");
                _ESTADO_SAP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ESTADO_SAP");
                OnESTADO_SAPChanged();
            }
        }
        private global::System.String _ESTADO_SAP;
        partial void OnESTADO_SAPChanging(global::System.String value);
        partial void OnESTADO_SAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MES_REGISTRO
        {
            get
            {
                return _MES_REGISTRO;
            }
            set
            {
                OnMES_REGISTROChanging(value);
                ReportPropertyChanging("MES_REGISTRO");
                _MES_REGISTRO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MES_REGISTRO");
                OnMES_REGISTROChanged();
            }
        }
        private global::System.String _MES_REGISTRO;
        partial void OnMES_REGISTROChanging(global::System.String value);
        partial void OnMES_REGISTROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MONEDA
        {
            get
            {
                return _MONEDA;
            }
            set
            {
                OnMONEDAChanging(value);
                ReportPropertyChanging("MONEDA");
                _MONEDA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MONEDA");
                OnMONEDAChanged();
            }
        }
        private global::System.String _MONEDA;
        partial void OnMONEDAChanging(global::System.String value);
        partial void OnMONEDAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NUMERO_ANTICIPO_SAP
        {
            get
            {
                return _NUMERO_ANTICIPO_SAP;
            }
            set
            {
                OnNUMERO_ANTICIPO_SAPChanging(value);
                ReportPropertyChanging("NUMERO_ANTICIPO_SAP");
                _NUMERO_ANTICIPO_SAP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NUMERO_ANTICIPO_SAP");
                OnNUMERO_ANTICIPO_SAPChanged();
            }
        }
        private global::System.String _NUMERO_ANTICIPO_SAP;
        partial void OnNUMERO_ANTICIPO_SAPChanging(global::System.String value);
        partial void OnNUMERO_ANTICIPO_SAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NUMERO_FACTURA_REFERENCIA
        {
            get
            {
                return _NUMERO_FACTURA_REFERENCIA;
            }
            set
            {
                OnNUMERO_FACTURA_REFERENCIAChanging(value);
                ReportPropertyChanging("NUMERO_FACTURA_REFERENCIA");
                _NUMERO_FACTURA_REFERENCIA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NUMERO_FACTURA_REFERENCIA");
                OnNUMERO_FACTURA_REFERENCIAChanged();
            }
        }
        private global::System.String _NUMERO_FACTURA_REFERENCIA;
        partial void OnNUMERO_FACTURA_REFERENCIAChanging(global::System.String value);
        partial void OnNUMERO_FACTURA_REFERENCIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MENSAJE_SAP
        {
            get
            {
                return _MENSAJE_SAP;
            }
            set
            {
                OnMENSAJE_SAPChanging(value);
                ReportPropertyChanging("MENSAJE_SAP");
                _MENSAJE_SAP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MENSAJE_SAP");
                OnMENSAJE_SAPChanged();
            }
        }
        private global::System.String _MENSAJE_SAP;
        partial void OnMENSAJE_SAPChanging(global::System.String value);
        partial void OnMENSAJE_SAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FECHA_ESTADO_SAP
        {
            get
            {
                return _FECHA_ESTADO_SAP;
            }
            set
            {
                OnFECHA_ESTADO_SAPChanging(value);
                ReportPropertyChanging("FECHA_ESTADO_SAP");
                _FECHA_ESTADO_SAP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_ESTADO_SAP");
                OnFECHA_ESTADO_SAPChanged();
            }
        }
        private Nullable<global::System.DateTime> _FECHA_ESTADO_SAP;
        partial void OnFECHA_ESTADO_SAPChanging(Nullable<global::System.DateTime> value);
        partial void OnFECHA_ESTADO_SAPChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ecuapassModel", "FK_ECU_LIQUIDACION_PAGO_SENAE_FK", "ECU_LIQUIDACION_SENAE")]
        public ECU_LIQUIDACION_SENAE ECU_LIQUIDACION_SENAE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ECU_LIQUIDACION_SENAE>("ecuapassModel.FK_ECU_LIQUIDACION_PAGO_SENAE_FK", "ECU_LIQUIDACION_SENAE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ECU_LIQUIDACION_SENAE>("ecuapassModel.FK_ECU_LIQUIDACION_PAGO_SENAE_FK", "ECU_LIQUIDACION_SENAE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ECU_LIQUIDACION_SENAE> ECU_LIQUIDACION_SENAEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ECU_LIQUIDACION_SENAE>("ecuapassModel.FK_ECU_LIQUIDACION_PAGO_SENAE_FK", "ECU_LIQUIDACION_SENAE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ECU_LIQUIDACION_SENAE>("ecuapassModel.FK_ECU_LIQUIDACION_PAGO_SENAE_FK", "ECU_LIQUIDACION_SENAE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ecuapassModel", Name="ECU_LIQUIDACION_SENAE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ECU_LIQUIDACION_SENAE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ECU_LIQUIDACION_SENAE object.
        /// </summary>
        /// <param name="tRAMITE">Initial value of the TRAMITE property.</param>
        /// <param name="eSTADO">Initial value of the ESTADO property.</param>
        /// <param name="cODIGO_UNICO">Initial value of the CODIGO_UNICO property.</param>
        /// <param name="nUMERO_FACTURA">Initial value of the NUMERO_FACTURA property.</param>
        /// <param name="fECHA_LIQUIDACION">Initial value of the FECHA_LIQUIDACION property.</param>
        /// <param name="fECHA_VIGENCIA">Initial value of the FECHA_VIGENCIA property.</param>
        /// <param name="rAZON_SOCIAL">Initial value of the RAZON_SOCIAL property.</param>
        /// <param name="nUMERO_IDENTIFICACION">Initial value of the NUMERO_IDENTIFICACION property.</param>
        /// <param name="sUBTOTAL_SINIVA">Initial value of the SUBTOTAL_SINIVA property.</param>
        /// <param name="iVA">Initial value of the IVA property.</param>
        /// <param name="mONTO_TOTAL">Initial value of the MONTO_TOTAL property.</param>
        /// <param name="nUMERO_LIQUIDACION">Initial value of the NUMERO_LIQUIDACION property.</param>
        /// <param name="fECHA_REGISTRO">Initial value of the FECHA_REGISTRO property.</param>
        /// <param name="uSUARIO_REGISTRO">Initial value of the USUARIO_REGISTRO property.</param>
        /// <param name="eSTADO_PROCESO">Initial value of the ESTADO_PROCESO property.</param>
        public static ECU_LIQUIDACION_SENAE CreateECU_LIQUIDACION_SENAE(global::System.String tRAMITE, global::System.String eSTADO, global::System.Int64 cODIGO_UNICO, global::System.String nUMERO_FACTURA, global::System.DateTime fECHA_LIQUIDACION, global::System.DateTime fECHA_VIGENCIA, global::System.String rAZON_SOCIAL, global::System.String nUMERO_IDENTIFICACION, global::System.Decimal sUBTOTAL_SINIVA, global::System.Decimal iVA, global::System.Decimal mONTO_TOTAL, global::System.String nUMERO_LIQUIDACION, global::System.DateTime fECHA_REGISTRO, global::System.String uSUARIO_REGISTRO, global::System.String eSTADO_PROCESO)
        {
            ECU_LIQUIDACION_SENAE eCU_LIQUIDACION_SENAE = new ECU_LIQUIDACION_SENAE();
            eCU_LIQUIDACION_SENAE.TRAMITE = tRAMITE;
            eCU_LIQUIDACION_SENAE.ESTADO = eSTADO;
            eCU_LIQUIDACION_SENAE.CODIGO_UNICO = cODIGO_UNICO;
            eCU_LIQUIDACION_SENAE.NUMERO_FACTURA = nUMERO_FACTURA;
            eCU_LIQUIDACION_SENAE.FECHA_LIQUIDACION = fECHA_LIQUIDACION;
            eCU_LIQUIDACION_SENAE.FECHA_VIGENCIA = fECHA_VIGENCIA;
            eCU_LIQUIDACION_SENAE.RAZON_SOCIAL = rAZON_SOCIAL;
            eCU_LIQUIDACION_SENAE.NUMERO_IDENTIFICACION = nUMERO_IDENTIFICACION;
            eCU_LIQUIDACION_SENAE.SUBTOTAL_SINIVA = sUBTOTAL_SINIVA;
            eCU_LIQUIDACION_SENAE.IVA = iVA;
            eCU_LIQUIDACION_SENAE.MONTO_TOTAL = mONTO_TOTAL;
            eCU_LIQUIDACION_SENAE.NUMERO_LIQUIDACION = nUMERO_LIQUIDACION;
            eCU_LIQUIDACION_SENAE.FECHA_REGISTRO = fECHA_REGISTRO;
            eCU_LIQUIDACION_SENAE.USUARIO_REGISTRO = uSUARIO_REGISTRO;
            eCU_LIQUIDACION_SENAE.ESTADO_PROCESO = eSTADO_PROCESO;
            return eCU_LIQUIDACION_SENAE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TRAMITE
        {
            get
            {
                return _TRAMITE;
            }
            set
            {
                OnTRAMITEChanging(value);
                ReportPropertyChanging("TRAMITE");
                _TRAMITE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TRAMITE");
                OnTRAMITEChanged();
            }
        }
        private global::System.String _TRAMITE;
        partial void OnTRAMITEChanging(global::System.String value);
        partial void OnTRAMITEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESTADO
        {
            get
            {
                return _ESTADO;
            }
            set
            {
                OnESTADOChanging(value);
                ReportPropertyChanging("ESTADO");
                _ESTADO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ESTADO");
                OnESTADOChanged();
            }
        }
        private global::System.String _ESTADO;
        partial void OnESTADOChanging(global::System.String value);
        partial void OnESTADOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CODIGO_UNICO
        {
            get
            {
                return _CODIGO_UNICO;
            }
            set
            {
                if (_CODIGO_UNICO != value)
                {
                    OnCODIGO_UNICOChanging(value);
                    ReportPropertyChanging("CODIGO_UNICO");
                    _CODIGO_UNICO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CODIGO_UNICO");
                    OnCODIGO_UNICOChanged();
                }
            }
        }
        private global::System.Int64 _CODIGO_UNICO;
        partial void OnCODIGO_UNICOChanging(global::System.Int64 value);
        partial void OnCODIGO_UNICOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NUMERO_FACTURA
        {
            get
            {
                return _NUMERO_FACTURA;
            }
            set
            {
                OnNUMERO_FACTURAChanging(value);
                ReportPropertyChanging("NUMERO_FACTURA");
                _NUMERO_FACTURA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NUMERO_FACTURA");
                OnNUMERO_FACTURAChanged();
            }
        }
        private global::System.String _NUMERO_FACTURA;
        partial void OnNUMERO_FACTURAChanging(global::System.String value);
        partial void OnNUMERO_FACTURAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA_LIQUIDACION
        {
            get
            {
                return _FECHA_LIQUIDACION;
            }
            set
            {
                OnFECHA_LIQUIDACIONChanging(value);
                ReportPropertyChanging("FECHA_LIQUIDACION");
                _FECHA_LIQUIDACION = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_LIQUIDACION");
                OnFECHA_LIQUIDACIONChanged();
            }
        }
        private global::System.DateTime _FECHA_LIQUIDACION;
        partial void OnFECHA_LIQUIDACIONChanging(global::System.DateTime value);
        partial void OnFECHA_LIQUIDACIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA_VIGENCIA
        {
            get
            {
                return _FECHA_VIGENCIA;
            }
            set
            {
                OnFECHA_VIGENCIAChanging(value);
                ReportPropertyChanging("FECHA_VIGENCIA");
                _FECHA_VIGENCIA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_VIGENCIA");
                OnFECHA_VIGENCIAChanged();
            }
        }
        private global::System.DateTime _FECHA_VIGENCIA;
        partial void OnFECHA_VIGENCIAChanging(global::System.DateTime value);
        partial void OnFECHA_VIGENCIAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RAZON_SOCIAL
        {
            get
            {
                return _RAZON_SOCIAL;
            }
            set
            {
                OnRAZON_SOCIALChanging(value);
                ReportPropertyChanging("RAZON_SOCIAL");
                _RAZON_SOCIAL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RAZON_SOCIAL");
                OnRAZON_SOCIALChanged();
            }
        }
        private global::System.String _RAZON_SOCIAL;
        partial void OnRAZON_SOCIALChanging(global::System.String value);
        partial void OnRAZON_SOCIALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NUMERO_IDENTIFICACION
        {
            get
            {
                return _NUMERO_IDENTIFICACION;
            }
            set
            {
                OnNUMERO_IDENTIFICACIONChanging(value);
                ReportPropertyChanging("NUMERO_IDENTIFICACION");
                _NUMERO_IDENTIFICACION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NUMERO_IDENTIFICACION");
                OnNUMERO_IDENTIFICACIONChanged();
            }
        }
        private global::System.String _NUMERO_IDENTIFICACION;
        partial void OnNUMERO_IDENTIFICACIONChanging(global::System.String value);
        partial void OnNUMERO_IDENTIFICACIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SUBTOTAL_SINIVA
        {
            get
            {
                return _SUBTOTAL_SINIVA;
            }
            set
            {
                OnSUBTOTAL_SINIVAChanging(value);
                ReportPropertyChanging("SUBTOTAL_SINIVA");
                _SUBTOTAL_SINIVA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SUBTOTAL_SINIVA");
                OnSUBTOTAL_SINIVAChanged();
            }
        }
        private global::System.Decimal _SUBTOTAL_SINIVA;
        partial void OnSUBTOTAL_SINIVAChanging(global::System.Decimal value);
        partial void OnSUBTOTAL_SINIVAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IVA
        {
            get
            {
                return _IVA;
            }
            set
            {
                OnIVAChanging(value);
                ReportPropertyChanging("IVA");
                _IVA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IVA");
                OnIVAChanged();
            }
        }
        private global::System.Decimal _IVA;
        partial void OnIVAChanging(global::System.Decimal value);
        partial void OnIVAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MONTO_TOTAL
        {
            get
            {
                return _MONTO_TOTAL;
            }
            set
            {
                OnMONTO_TOTALChanging(value);
                ReportPropertyChanging("MONTO_TOTAL");
                _MONTO_TOTAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTO_TOTAL");
                OnMONTO_TOTALChanged();
            }
        }
        private global::System.Decimal _MONTO_TOTAL;
        partial void OnMONTO_TOTALChanging(global::System.Decimal value);
        partial void OnMONTO_TOTALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NUMERO_LIQUIDACION
        {
            get
            {
                return _NUMERO_LIQUIDACION;
            }
            set
            {
                OnNUMERO_LIQUIDACIONChanging(value);
                ReportPropertyChanging("NUMERO_LIQUIDACION");
                _NUMERO_LIQUIDACION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NUMERO_LIQUIDACION");
                OnNUMERO_LIQUIDACIONChanged();
            }
        }
        private global::System.String _NUMERO_LIQUIDACION;
        partial void OnNUMERO_LIQUIDACIONChanging(global::System.String value);
        partial void OnNUMERO_LIQUIDACIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA_REGISTRO
        {
            get
            {
                return _FECHA_REGISTRO;
            }
            set
            {
                OnFECHA_REGISTROChanging(value);
                ReportPropertyChanging("FECHA_REGISTRO");
                _FECHA_REGISTRO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_REGISTRO");
                OnFECHA_REGISTROChanged();
            }
        }
        private global::System.DateTime _FECHA_REGISTRO;
        partial void OnFECHA_REGISTROChanging(global::System.DateTime value);
        partial void OnFECHA_REGISTROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USUARIO_REGISTRO
        {
            get
            {
                return _USUARIO_REGISTRO;
            }
            set
            {
                OnUSUARIO_REGISTROChanging(value);
                ReportPropertyChanging("USUARIO_REGISTRO");
                _USUARIO_REGISTRO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USUARIO_REGISTRO");
                OnUSUARIO_REGISTROChanged();
            }
        }
        private global::System.String _USUARIO_REGISTRO;
        partial void OnUSUARIO_REGISTROChanging(global::System.String value);
        partial void OnUSUARIO_REGISTROChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESTADO_PROCESO
        {
            get
            {
                return _ESTADO_PROCESO;
            }
            set
            {
                OnESTADO_PROCESOChanging(value);
                ReportPropertyChanging("ESTADO_PROCESO");
                _ESTADO_PROCESO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ESTADO_PROCESO");
                OnESTADO_PROCESOChanged();
            }
        }
        private global::System.String _ESTADO_PROCESO;
        partial void OnESTADO_PROCESOChanging(global::System.String value);
        partial void OnESTADO_PROCESOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FECHA_PROCESO
        {
            get
            {
                return _FECHA_PROCESO;
            }
            set
            {
                OnFECHA_PROCESOChanging(value);
                ReportPropertyChanging("FECHA_PROCESO");
                _FECHA_PROCESO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_PROCESO");
                OnFECHA_PROCESOChanged();
            }
        }
        private Nullable<global::System.DateTime> _FECHA_PROCESO;
        partial void OnFECHA_PROCESOChanging(Nullable<global::System.DateTime> value);
        partial void OnFECHA_PROCESOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USUARIO_PROCESO
        {
            get
            {
                return _USUARIO_PROCESO;
            }
            set
            {
                OnUSUARIO_PROCESOChanging(value);
                ReportPropertyChanging("USUARIO_PROCESO");
                _USUARIO_PROCESO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USUARIO_PROCESO");
                OnUSUARIO_PROCESOChanged();
            }
        }
        private global::System.String _USUARIO_PROCESO;
        partial void OnUSUARIO_PROCESOChanging(global::System.String value);
        partial void OnUSUARIO_PROCESOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TIPO
        {
            get
            {
                return _TIPO;
            }
            set
            {
                OnTIPOChanging(value);
                ReportPropertyChanging("TIPO");
                _TIPO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TIPO");
                OnTIPOChanged();
            }
        }
        private global::System.String _TIPO;
        partial void OnTIPOChanging(global::System.String value);
        partial void OnTIPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NUMERO_BOOKING
        {
            get
            {
                return _NUMERO_BOOKING;
            }
            set
            {
                OnNUMERO_BOOKINGChanging(value);
                ReportPropertyChanging("NUMERO_BOOKING");
                _NUMERO_BOOKING = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NUMERO_BOOKING");
                OnNUMERO_BOOKINGChanged();
            }
        }
        private global::System.String _NUMERO_BOOKING;
        partial void OnNUMERO_BOOKINGChanging(global::System.String value);
        partial void OnNUMERO_BOOKINGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ROL
        {
            get
            {
                return _ROL;
            }
            set
            {
                OnROLChanging(value);
                ReportPropertyChanging("ROL");
                _ROL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ROL");
                OnROLChanged();
            }
        }
        private global::System.String _ROL;
        partial void OnROLChanging(global::System.String value);
        partial void OnROLChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ecuapassModel", "FK_ECU_LIQUIDACION_PAGO_SENAE_FK", "ECU_LIQUIDACION_PAGO_SENAE")]
        public EntityCollection<ECU_LIQUIDACION_PAGO_SENAE> ECU_LIQUIDACION_PAGO_SENAE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ECU_LIQUIDACION_PAGO_SENAE>("ecuapassModel.FK_ECU_LIQUIDACION_PAGO_SENAE_FK", "ECU_LIQUIDACION_PAGO_SENAE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ECU_LIQUIDACION_PAGO_SENAE>("ecuapassModel.FK_ECU_LIQUIDACION_PAGO_SENAE_FK", "ECU_LIQUIDACION_PAGO_SENAE", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
